### ISSUE TITLE
Presentation files naming - year, then month?

### ISSUE THREAD

**Issue by codepainters** [Rust-Wroclaw/rust-wroclaw#16]
Minor, but annoying - currently presentation files are named `MM-YYYY-whatever`. 
How about swapping year and month for better sorting?

**Comment by codepainters** [comment]
...and can be done with simple
```
rename 's/^(\d{2})-(\d{4})/$2-$1/' *
```

**Comment by MaciekTalaska** [comment]
thanks!

done: https://github.com/Rust-Wroclaw/rust-wroclaw/commit/560bd96717f032f8390308e6fcbe7648fce52159

**Comment by codepainters** [comment]
Thanks, but it was about the actual file names, not the `README` file - I simply wanted the files to sort in chronological order when I `ls` them :)

**Comment by ignlg** [comment]
Agree with the request. Any `YYYYMMDD` date format, with or without separators, would do the trick.

**Comment by MaciekTalaska** [comment]
@ignlg @codepainters  that makes sense! I am more than happy to merge a PR - feel free to rename the files as you wish

**Comment by codepainters** [comment]
Not sure why I can't link issue <-> pull req., but PR https://github.com/Rust-Wroclaw/rust-wroclaw/pull/18 renames the presentations.

**Comment by MaciekTalaska** [comment]
@codepainters thank you!
